CREATE TABLE CAR_TYPES(

TYPE_ID NUMBER(10) PRIMARY KEY,
TYPE_NAME VARCHAR2(25)

);

INSERT INTO CAR_TYPES VALUES ( 1, 'Hatchback');
INSERT INTO CAR_TYPES VALUES ( 2, 'Mini');
INSERT INTO CAR_TYPES VALUES ( 3, 'Sedan');
INSERT INTO CAR_TYPES VALUES ( 4, 'SUV');

CREATE TABLE CAR_DETAILS(
REG_NO Varchar2(100) PRIMARY KEY,
MANUFACTURER_NAME_MDL VARCHAR2(100),
COMPANY_NAME varchar2(100) REFERENCES,
CAR_TYPE varchar2(100) REFERENCES CAR_TYPES(TYPE_ID),
CURRENT_STATUS VARCHAR2(30) CHECK IN (BKD,UNBKD) , DEFAULT 'UNBKD'
);
